events {}

http {
  # Round Robin upstream (mặc định của nginx) 
  upstream web_backend {
    server web-frontend-server1:80;
    server web-frontend-server2:80;
    # Nginx tự luân phiên request 1→2→1→2... (Round Robin)
  }

  server {
    listen 80;

    # Load-balanced web frontend
    location / {
      proxy_pass         http://web_backend;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
      proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    # Application backend API
    location /api/ {
      proxy_pass         http://application-backend-server:8081/;
      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
    }
    
    # Keycloak
    location /auth/ {
      proxy_pass http://authentication-identity-server:8080/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
